package arch

import (
	"bytes"
	"testing"
)

// The expected addresses in this file were generated by running
// arch_program::pubkey::Pubkey::find_program_address from the arch-network
// Rust sources with the same inputs.

func TestFindProgramAddressMatchesRustFixture(t *testing.T) {
	pda, bump, err := FindProgramAddress(
		[][]byte{[]byte("vault"), {1, 2, 3}},
		TokenProgramID,
	)
	if err != nil {
		t.Fatal(err)
	}
	want := mustPubkey(t, "df5bd932f5eb0376acdcba271a8479f9ee38d8af308b60a1ded6dc66544ecfe4")
	if pda != want {
		t.Errorf("pda = %s, want %s", pda, want)
	}
	if bump != 255 {
		t.Errorf("bump = %d, want 255", bump)
	}
}

func TestAssociatedTokenAddressMatchesRustFixture(t *testing.T) {
	// The Rust fixture used wallet [7u8; 32] and mint [9u8; 32].
	var wallet, mint Pubkey
	for i := range wallet {
		wallet[i] = 7
		mint[i] = 9
	}
	pda, bump, err := AssociatedTokenAddress(wallet, mint)
	if err != nil {
		t.Fatal(err)
	}
	want := mustPubkey(t, "fc6c1f3abecf0a478af7f97595a541f1dbac2812c980b3e8bb2804538931a8a4")
	if pda != want {
		t.Errorf("ata = %s, want %s", pda, want)
	}
	if bump != 255 {
		t.Errorf("bump = %d, want 255", bump)
	}
}

func TestCreateProgramAddressSeedLimits(t *testing.T) {
	if _, err := CreateProgramAddress(make([][]byte, MaxSeeds+1), TokenProgramID); err == nil {
		t.Error("expected error for too many seeds")
	}
	if _, err := CreateProgramAddress([][]byte{make([]byte, MaxSeedLen+1)}, TokenProgramID); err == nil {
		t.Error("expected error for over-long seed")
	}
	if _, err := CreateProgramAddress([][]byte{make([]byte, MaxSeedLen)}, TokenProgramID); err != nil {
		t.Errorf("unexpected error at seed length limit: %v", err)
	}
}

func TestFindProgramAddressAppendsBumpAsSeed(t *testing.T) {
	seeds := [][]byte{[]byte("vault"), {1, 2, 3}}
	pda, bump, err := FindProgramAddress(seeds, TokenProgramID)
	if err != nil {
		t.Fatal(err)
	}
	direct, err := CreateProgramAddress(append(append([][]byte{}, seeds...), []byte{bump}), TokenProgramID)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(pda[:], direct[:]) {
		t.Error("FindProgramAddress result does not match CreateProgramAddress with the bump appended")
	}
}

func mustPubkey(t *testing.T, hexStr string) Pubkey {
	t.Helper()
	p, err := PubkeyFromHex(hexStr)
	if err != nil {
		t.Fatal(err)
	}
	return p
}
